# Topic Modeling: Descubriendo Temáticas en los Comentarios de Facebook

## Cargar el archivo
Se extrajeron 1,569 comentarios de septiembre y octubre año 2020 en los que se menciona a CitiBanamex

In [ ]:
# pip install nltk
# !pip install networkx
# import nltk
# nltk.download("stopwords")

In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import string
import re

import nltk
from nltk.corpus import stopwords
# nltk.download('stopwords')
from nltk.stem import SnowballStemmer

from sklearn.feature_extraction.text import CountVectorizer

import networkx as nx
# import nltkimport networkx as nx
from networkx.algorithms import community

stop_words_sp = set(stopwords.words('spanish'))

In [14]:
df = pd.read_csv("../data/raw/BanamexFace.csv")
df.head()

,pub,usr,likes,com,fec,hor,sent,tag
0,20200805,Dayana Tinajero,18,"no inventen, acabo de llamar al call center y ...",2020-08-06,11:37:00,n,seguridad
1,20200805,Salma Madrid,5,"pesimo servicio de call center, contestan con ...",2020-08-06,12:56:00,n,atencion_call
2,20200805,Dayana Tinajero,3,"mejor voy a sucursal, ya no me da confianza na...",2020-08-06,13:20:00,n,seguridad
3,20200805,Lissy Jimenez,0,citibanamex podrían decirme dónde puedo llamar...,2020-08-06,16:04:00,o,consulta
4,20200805,Lissy Jimenez,0,citibanamex gracias si me gustaría saber cuand...,2020-08-06,16:23:00,o,consulta

### Removiendo los signos de puntuación

In [15]:
import sys
sys.path.append("../src")

from text_preprocessing import clean_text

In [16]:
# Aplicamos limpieza de texto en los comentarios
# -----------------
df['com_clean'] = df['com'].apply(clean_text)

df.head()

,pub,usr,likes,com,fec,hor,sent,tag,com_clean
0,20200805,Dayana Tinajero,18,"no inventen, acabo de llamar al call center y ...",2020-08-06,11:37:00,n,seguridad,inventen acabo llamar call center contesto chi...
1,20200805,Salma Madrid,5,"pesimo servicio de call center, contestan con ...",2020-08-06,12:56:00,n,atencion_call,pesimo servicio call center contestan voz floj...
2,20200805,Dayana Tinajero,3,"mejor voy a sucursal, ya no me da confianza na...",2020-08-06,13:20:00,n,seguridad,mejor voy sucursal da confianza personas q con...
3,20200805,Lissy Jimenez,0,citibanamex podrían decirme dónde puedo llamar...,2020-08-06,16:04:00,o,consulta,citibanamex podrían decirme dónde puedo llamar...
4,20200805,Lissy Jimenez,0,citibanamex gracias si me gustaría saber cuand...,2020-08-06,16:23:00,o,consulta,citibanamex gracias si gustaría saber vence pr...

### Estadísticos básicos de entendimiento